# Generated by Django 4.2.11 on 2026-01-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('turf', 'Turf booking'), ('restaurant', 'Restaurant bill sharing'), ('trip', 'Trip booking'), ('party', 'Party / Celebration'), ('custom', 'Custom event')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('due_pay_date', models.DateField()),
                ('event_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('persons_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to='accounts.user')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['status', 'event_date'], name='events_status_4e8a13_idx'), models.Index(fields=['created_by', 'status'], name='events_created_d21bbc_idx')],
            },
        ),
    ]
