# Generated by Django 4.2.11 on 2026-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
