# Generated by Django 4.2.11 on 2026-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
