# Generated by Django 4.2.11 on 2026-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_address_event_location_event_custom_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='due_pay_date',
            new_name='due_pay_date_time',
        ),
    ]
