# Generated by Django 4.2.11 on 2026-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_due_pay_date_event_due_pay_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due_pay_date_time',
            field=models.DateTimeField(),
        ),
    ]
