# Generated by Django 4.2.11 on 2026-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_due_pay_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='due_pay_before_event_start',
            field=models.BooleanField(default=True, help_text='If True, due_pay_date_time must be before event start. If False, it can be after event start.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_pay_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
