# Generated by Django 4.2.11 on 2026-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_due_pay_before_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(help_text='Any category (e.g., Turf booking, Restaurant, Trip, Party, etc.)', max_length=200),
        ),
    ]
