# Generated by Django 4.2.11 on 2026-01-29 07:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified'),
        ('events', '0002_alter_event_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_id', models.CharField(help_text='Unique webhook ID from Razorpay', max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('payment.captured', 'Payment Captured'), ('payment.failed', 'Payment Failed'), ('payment.authorized', 'Payment Authorized'), ('payout.processed', 'Payout Processed'), ('payout.failed', 'Payout Failed'), ('payout.reversed', 'Payout Reversed')], max_length=50)),
                ('payload', models.JSONField(help_text='Full webhook payload from Razorpay')),
                ('signature', models.CharField(help_text='Signature for verification', max_length=255)),
                ('signature_verified', models.BooleanField(default=False, help_text='Whether signature was verified')),
                ('processed', models.BooleanField(default=False, help_text='Whether webhook was processed')),
                ('processing_status', models.CharField(blank=True, help_text='SUCCESS or error message', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('razorpay_entity_id', models.CharField(blank=True, help_text='Entity ID from webhook', max_length=100, null=True)),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook_id'], name='webhook_log_webhook_3c6442_idx'), models.Index(fields=['event_type'], name='webhook_log_event_t_78002f_idx'), models.Index(fields=['processed'], name='webhook_log_process_8f7aab_idx'), models.Index(fields=['razorpay_entity_id'], name='webhook_log_razorpa_9939fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('razorpay_customer_id', models.CharField(blank=True, help_text='Razorpay customer ID for this user', max_length=50, null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last synced with Razorpay', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.user')),
            ],
            options={
                'db_table': 'user_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received from Participant'), ('PAYOUT_INITIATED', 'Payout to Vendor Initiated'), ('PAYOUT_SUCCESS', 'Payout Success'), ('PAYOUT_FAILED', 'Payout Failed - Refund'), ('EVENT_REFUND', 'Event Cancelled - Refund'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment by Admin'), ('REVERSAL', 'Transaction Reversal')], max_length=50)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Unique key for idempotent operations', max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger', to='accounts.user')),
            ],
            options={
                'db_table': 'wallet_ledgers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_ledg_user_id_623d3d_idx'), models.Index(fields=['razorpay_payment_id'], name='wallet_ledg_razorpa_3aea1f_idx'), models.Index(fields=['razorpay_payout_id'], name='wallet_ledg_razorpa_fcbce8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RazorpayPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('razorpay_payout_id', models.CharField(blank=True, help_text='Payout ID from Razorpay', max_length=50, null=True, unique=True)),
                ('razorpay_contact_id', models.CharField(blank=True, help_text='Contact ID for vendor in Razorpay', max_length=50, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, help_text='Fund account ID in Razorpay', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('settlement_type', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CARD', 'Card')], default='UPI', max_length=20)),
                ('settlement_upi', models.CharField(blank=True, help_text='UPI ID for payout', max_length=100, null=True)),
                ('settlement_bank_account', models.CharField(blank=True, help_text='Bank account number', max_length=100, null=True)),
                ('settlement_ifsc', models.CharField(blank=True, help_text='IFSC code for bank transfer', max_length=20, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='INITIATED', max_length=20)),
                ('webhook_received', models.BooleanField(default=False)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payouts', to='events.event')),
                ('vendor', models.ForeignKey(help_text='Event creator (vendor)', on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payouts', to='accounts.user')),
            ],
            options={
                'db_table': 'razorpay_payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_payout_id'], name='razorpay_pa_razorpa_d4b0b6_idx'), models.Index(fields=['event'], name='razorpay_pa_event_i_2d3482_idx'), models.Index(fields=['vendor'], name='razorpay_pa_vendor__65ef87_idx'), models.Index(fields=['status'], name='razorpay_pa_status_2a2855_idx')],
                'unique_together': {('event', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('razorpay_order_id', models.CharField(help_text='Order ID from Razorpay', max_length=50, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Payment ID after successful payment', max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ATTEMPTED', 'Attempted'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('webhook_received', models.BooleanField(default=False, help_text='Whether payment webhook was received')),
                ('webhook_verified', models.BooleanField(default=False, help_text='Whether payment webhook was verified')),
                ('receipt', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='events.event')),
                ('participant', models.ForeignKey(help_text='User joining the event', on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='accounts.user')),
            ],
            options={
                'db_table': 'razorpay_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='razorpay_or_razorpa_1ee784_idx'), models.Index(fields=['razorpay_payment_id'], name='razorpay_or_razorpa_291657_idx'), models.Index(fields=['event', 'participant'], name='razorpay_or_event_i_cb529e_idx'), models.Index(fields=['status'], name='razorpay_or_status_b378dd_idx')],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
