# Generated by Django 4.2.11 on 2026-01-29 11:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_address'),
        ('accounts', '0004_user_email_verified'),
        ('payments', '0002_webhooklog_userwallet_walletledger_razorpaypayout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='e.g., Accommodation, Transport, etc.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('settlement_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='events.event')),
                ('settled_by', models.ForeignKey(help_text='Owner/Admin who initiated settlement', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_settlements', to='accounts.user')),
                ('vendor', models.ForeignKey(help_text='Event creator receiving payment', on_delete=django.db.models.deletion.CASCADE, related_name='received_settlements', to='accounts.user')),
            ],
            options={
                'db_table': 'event_settlements',
                'ordering': ['-settlement_date'],
                'indexes': [models.Index(fields=['event', 'status'], name='event_settl_event_i_77c29a_idx'), models.Index(fields=['vendor'], name='event_settl_vendor__35cddd_idx'), models.Index(fields=['settled_by'], name='event_settl_settled_abd4a8_idx')],
            },
        ),
    ]
