# Generated by Django 4.2.11 on 2026-01-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_eventsettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.BigIntegerField()),
                ('initiated_by', models.BigIntegerField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_upi', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='vendor_paym_event_e9904e_idx'), models.Index(fields=['status'], name='vendor_paym_status_cf3510_idx'), models.Index(fields=['razorpay_payout_id'], name='vendor_paym_razorpa_b36c12_idx')],
            },
        ),
    ]
