# Generated by Django 4.2.11 on 2026-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_vendorpaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcollectiontransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID for this transaction', max_length=50, null=True),
        ),
    ]
