# Generated by Django 4.2.11 on 2026-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_eventcollectiontransaction_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcollectiontransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID for this transaction', max_length=50, null=True),
        ),
    ]
