# Generated by Django 4.2.11 on 2026-01-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Admin Summary'), ('users', 'Admin Users'), ('events', 'Admin Events'), ('payments', 'Admin Payments'), ('payouts', 'Admin Payouts'), ('user-summary', 'User Summary'), ('user-events', 'User Events'), ('user-payments', 'User Payments'), ('user-wallet', 'User Wallet')], max_length=50)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to='accounts.user')),
            ],
            options={
                'db_table': 'report_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
